#!/bin/bash
#
# Sets up the ObjectiveHaskell project itself.

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

set -o errexit

echo "*** Updating submodules..."
git submodule sync --quiet
git submodule update --init
git submodule foreach --recursive --quiet "git submodule sync --quiet && git submodule update --init"

echo "*** Generating project xcconfigs..."
"$SCRIPT_DIR/genconfig" ObjectiveHaskell/ObjectiveHaskell.xcconfig "External/ReactiveCocoa/ReactiveCocoaFramework/ReactiveCocoa/libextobjc/Configuration/Mac OS X/Mac-StaticLibrary.xcconfig"
"$SCRIPT_DIR/genconfig" ObjectiveHaskellTests/ObjectiveHaskellTests.xcconfig "External/ReactiveCocoa/ReactiveCocoaFramework/ReactiveCocoa/libextobjc/Configuration/Mac OS X/Mac-Application.xcconfig"
